### ISSUE TITLE
"SyntaxError: Unexpected token ..." with: "/usr/lib/node_modules/unshrtn/node_modules/metaweb/metaweb.js:148 return {...result, ...normalized}" 

### ISSUE THREAD

**Issue by remagio** [DocNow/unshrtn#15]
I updated my unshrtn instances to current version but I get this when starting it:
```
$: unshrtn
/usr/lib/node_modules/unshrtn/node_modules/metaweb/metaweb.js:148
  return {...result, ...normalized}
          ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/unshrtn/unshrtn.js:9:15)
```
This error is from a fresh DigitalOcean VM with current Ubuntu LTS 16.04.5 and current nodejs LTS v6.12.0. Same on debians/OSXs boxes. Any idea?

**Comment by remagio** [comment]
Followup, the docker way workes fine. Just if you NPM's or clone install it fails. I reviewed sources too but I can't find what missing or wrong from the docker image/instance. On the same debians/ubuntus/osx the docker way works but not from sources or by npm.

**Comment by edsu** [comment]
Hmm must have been an older version of Node that didn't have the spread operator?

**Comment by remagio** [comment]
Ha, at the time was the current LTS release. But I forgot this still open, 1y later It worked so I'd close this issue, thx Ed.

**Comment by edsu** [comment]
Thanks @remagio!
